### ISSUE TITLE
Feature request: Division and remainder operators

### ISSUE THREAD

**Issue by arslanarm** [dhruvrajvanshi/hades-lang#74]
As I have seen from the source code, parser supports only `+` and `-` operators. 
I was trying to write a simple function to convert `Int` to `*Byte` but the absence of `/ `and `%` operators caught me of guard.

**Comment by dhruvrajvanshi** [comment]
https://github.com/dhruvrajvanshi/hades-lang/pull/79
https://github.com/dhruvrajvanshi/hades-lang/pull/80

These 2 pull requests add initial support for these operators over float types.

In the long term, we would like to have these operators supported by traits, but right now, I don't want to deal with the complexity of handling type inference for these.

Documenting the complication here for future reference

```
trait Div[Lhs, Rhs] {
   type Result
   def div(lhs: Lhs, rhs: Rhs): Result
}

implementation Div[f64, u32] { ...}
implementation Div[f64, u64] { ... }

def main(): Void {
  val x: f64
  x / 23.2 // type of 23.2 is ambiguous here because of 2 possible impl clauses that are valid.
               // since float literals can't be inferred in general (only checked) in our bidirectional type checker
               // we don't know which type to assign to the literal
}
